"""initial_revision

Revision ID: 1997acc83b24
Revises: 
Create Date: 2020-08-03 16:19:34.148616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1997acc83b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.CHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_key', mysql.CHAR(length=80), nullable=True),
    sa.Column('auth_value', mysql.CHAR(length=10), nullable=True),
    sa.Column('phone_num', mysql.CHAR(length=20), nullable=True),
    sa.Column('expiration', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.CHAR(length=15), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('nick_name', mysql.CHAR(length=50), nullable=True),
    sa.Column('picture', mysql.TEXT(), nullable=True),
    sa.Column('registered_at', mysql.DATETIME(), nullable=True),
    sa.Column('religion', mysql.TEXT(), nullable=True),
    sa.Column('smoke', sa.BOOLEAN(), nullable=True),
    sa.Column('job', mysql.TEXT(), nullable=True),
    sa.Column('school', mysql.TEXT(), nullable=True),
    sa.Column('major', mysql.TEXT(), nullable=True),
    sa.Column('company', mysql.TEXT(), nullable=True),
    sa.Column('is_couple', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nick_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', mysql.TEXT(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', mysql.TEXT(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=False),
    sa.Column('activated', sa.BOOLEAN(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', mysql.TEXT(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='user_question_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('match_questions')
    op.drop_table('answers')
    op.drop_table('user_sessions')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('sms_auth')
    op.drop_table('categories')
    # ### end Alembic commands ###
